#pragma once
#include <SFML/Graphics.hpp>
#include <Windows.h>
#include "View.h"
#include "math.h"
#include "Player.h"
#include "Globals.h"
#include "Food.h"
#include "Enemy.h"
#include "Functions.h"
#include <string>
#include <iostream>